export enum Strings {
  EMPTY = '',
  QUIT = 'Çıkış',
  HEADERLESS = 'Başlıksız',
  PARAMETERS = 'Parametreler',
  QRCODE_SCAN = 'QR Kod Tara',
  SORT_BY = 'Sırala',
  CLOSE = 'Kapat',
  DELETE = 'Sil',
  YES = 'Evet',
  NO = 'Hayır',
  CANCEL = 'İptal',
  ADD = 'Ekle',
  UPDATE = 'Güncelle',
  SAVE = 'Kaydet',
  PASSIVE = 'Pasif',
  DATE = 'Tarih',
  DAY = 'Gün',
  MONTH = 'Ay',
  MONTHS = 'Aylar',
  YEAR = 'Yıl',
  WEEK = 'Hafta',
  TODAY = 'Bugün',
  SEARCH = 'Ara',
  SEARCH2 = 'Arama',
  ALLOF = 'Tümü',
  RECORD = 'Kayıt',
  TITLE = 'Başlık',
  SERVICE_ERROR = 'Servis Hatası',
  LOADING = 'Yükleniyor...',
  COMPLETED = 'Tamamlandı',
  NO_DATA = 'Veri getirilemiyor',
  NOT_AUTHORIZATION = 'Bu sayfaya giriş yetkiniz bulunmamaktadır',
  NOT_FOUND_PAGE = 'Sayfa Bulunamadı',
  UNSPECIFIED = 'Belirtilmedi',
  DESCRIPTION = 'Açıklama',
  ENTER_DESCRIPTION = 'Açıklama giriniz',

  TOOLS = 'Araçlar',
  CHOOSE_UNIT = 'Birim Seçiniz',
  UNIT_NOT_FOUND = 'Birim Bulunamadı',
  CHOOSE_GROUP = 'Grup Seçiniz',
  GROUP_NOT_FOUND = 'Grup Bulunamadı',
  CALCULATION = 'Hesaplama',
  CALCULATION_TOOLS = 'Hesaplama Araçları',
  UNITS = 'Birimler',
  SHEET = 'Sac',
  PROFILE = 'Profil',
  PIPE = 'Boru',
  MILE = 'Mil',
  HEXAGON = 'Altıgen',
  SQUARE = 'Kare',
  MATERIAL = 'Malzeme',

  IS_EQUAL = 'Eşittir',
  IS_NOT_EQUAL = 'Eşit Değildir',
  IS_LESS = 'Küçüktür',
  IS_LESS_EQUAL = 'Küçük Eşittir',
  IS_GREATER = 'Büyüktür',
  IS_GREATER_EQUAL = 'Büyük Eşittir',
  IS_NULL = 'Değer Atanmamış',
  IS_NOT_NULL = 'Değer Atanmış',
  START_WITH = 'Başlayan',
  END_WITH = 'Biten',
  DOES_CONTAIN = 'İçeren',
  DOES_NOT_CONTAIN = 'İçermeyen',

  PERSONS = 'Kişiler',

  EMPLOYEES = 'Personeller',
  EMPLOYEE_NAME = 'Personel Adı',
  EMPLOYEE_TITLE = 'Görevi',
  IDENTITY_NUMBER = 'Kimlik Numarası',
  EMAIL = 'Email',
  EMAIL_ADDRESS = 'Email Adresi',
  EMPLOYEE_LIST = 'Personel Listesi',
  EMPLOYEE_ADD = 'Personel Ekle',
  EMPLOYEE_INFORMATION_EDIT = 'Personel Bilgilerini Düzenle',
  EMPLOYEE_ACTIVE_PASSIVE = 'Personel Aktifleştir/Pasifleştir',
  PASSIVE_EMPLOYEE_LIST = 'Pasif Personel Listesi',
  EMPLOYEE_NOT_FOUND = 'Kayıtlı personel bulunamadı',
  EMPLOYEE_NOT_FOUND2 = 'Personel Bulunamadı',
  PASSIVE_EMPLOYEE_NOT_FOUND = 'Pasif personel bulunamadı',
  CHOOSE_EMPLOYEE = 'Personel Seçiniz',
  EMPLOYEE_ADDED = 'Personel eklendi',
  EMPLOYEE_UPDATED = 'Personel güncellendi',
  EMPLOYEE_PASSIVED = 'Personel pasif hale getirildi',
  EMPLOYEE_ACTIVED = 'Personel aktif hale getirildi',

  LOGIN = 'Giriş',
  LOGIN_TEXT = 'Lütfen giriş yapınız',
  USER_NAME = 'Kullanıcı Adı',
  PASSWORD = 'Şifre',
}

export const PASSWORD_RULES: string[] = [
  'Şifre en az 8 karakter olmalıdır.',
  'Şifre içerisinde en az bir adet harf bulunmalıdır.',
  'Şifre içerisinde en az bir adet rakam bulunmalıdır.',
];
